apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: desenvolvimento
  labels:
    app: nginx
spec:
  #type: ClusterIP Acessivel apenas dentro do cluster.
  type: NodePort #Acessivel fora do cluster
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007